package edu.odu.cs.cs350;

import java.util.Collection;

/** class for holding all data related to a CSS file for storing inside the Website class
 * @author austi
 *
 */
public class CSS {
 
	/** String name the filename of the CSS file
	 * 
	 */
	String name;
	
	/** unique ID for individual CSS stylesheet
	 * 
	 */
	int id;
	
	/** size of the file
	 * 
	 */
	long fileSize;
	
	/** Integer for internal (0) or external (1) styling
	 * 
	 */
	int classification;
	//string to hold the URI
	/**
	 * 
	 */
	String uri;
	/**array to hold the local pages each script is utilized on
	 * 
	 */
	Collection<Page> references;
	
	/** constructor for CSS sheet from data generated by analysis
	 * @param name name of the file passed in
	 * @param id unique id generated from analysis
	 * @param classification internal/external styling
	 * @param fileSize size of the file from analysis
	 * @param uri address of file from analysis
	 */
	CSS(String name, int id, int classification, long fileSize, String uri){
        this.name = name;
		this.id =  id;
        this.classification = classification;
        this.fileSize = fileSize;
        this.uri =  uri;
        System.out.println("-CSS Reference created-");

    }
}
