package edu.odu.cs.cs350;

import java.util.Collection;

/** Class to hold data for each individual image found in website analysis directory
 * @author austi
 *
 */
public class Image {
	/** title of image
	 * 
	 */
	String name;
	/** unique integer ID
	 * 
	 */
	int id;
	/** Integer for internal (0) or external (1)
	 * 
	 */
	int classification;
	/** file size of the image in kb
	 * 
	 */
	long fileSize;
	/** URI locator
	 * 
	 */
	String uri;
	/** Image constructor for taking in data from website analysis
	 * @param name title of image found in directory
	 * @param id integer id generated by analysis
	 * @param classification internal vs external image
	 * @param fileSize file size found in directory
	 * @param uri location of file in directory or external internet
	 */
	Image(String name, int id, int classification, long fileSize, String uri){
        this.name = name;
		this.id =  id;
        this.classification = classification;
        this.fileSize = fileSize;
        this.uri =  uri;
        System.out.println("-Image created-");

    }
	
	/** Array to hold unique ID of pages where this is referenced
	 * 
	 */
	Collection<Page> references;
}
