package edu.odu.cs.cs350;

import java.util.Collection;

/** Class to hold information of each Javascript file found in analysis
 * @author austi
 *
 */
public class JavaScript {
	/** string name of file
	 * 
	 */
	String name;
	/** unique integer ID
	 * 
	 */
	int id;
	/** Integer for internal (0) or external (1)
	 * 
	 */
	int classification;
	/** filesize
	 * 
	 */
	long fileSize;
	/** URI locator
	 * 
	 */
	String uri;
	/** Array to hold unique ID of pages where this is referenced
	 * 
	 */
	Collection<Page> references;
	/** Constructor to be used for passing WebsiteAnalysis data
	 * @param name name of JS function/file 
	 * @param id unique id generated by analysis for this JS reference
	 * @param classification internal/external classification
	 * @param fileSize filesize in kb found by analysis
	 * @param uri locator, internal file path or external path
	 */
	JavaScript(String name, int id, int classification, long fileSize, String uri){
        this.name = name;
		this.id =  id;
		this.classification = classification;
        this.fileSize = fileSize;
        this.uri =  uri;
        System.out.println("-JavaScript File created-");

    }
}
