package edu.odu.cs.cs350;

import java.util.Collection;

/** Class to store all internal, external, or intra-site links found by analysis
 * @author austi
 *
 */
public class Link {
	/** string name
	 * 
	 */
	String name;
	/** unique integer ID
	 * 
	 */
	String id;
	/** Link type: intra, internal or external
	 * 
	 */
	String classification;
	/** filesize in kb
	 * 
	 */
	long fileSize;
	/** URI locator
	 * 
	 */
	String uri;
	/** Array to hold unique ID of pages where this is referenced
	 * 
	 */
	Collection<Page> references;
	/** Constructor for each unique Link found by analysis
	 * @param name string name of file passed in by analysis
	 * @param id unique ID generated by analysis
	 * @param uri locator passed in by analysis
	 * @param classification intra, inter, or external file type passed in by analysis
	 */
	Link(String name, String id, String uri, String classification){
        this.name = name;
		this.id =  id;
		this.classification = classification;
        // this.fileSize = fileSize;
        this.uri =  uri;
        System.out.println("-Link Created-");
    }
}
