/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.odu.cs.cs350;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

public class AppTest {
	
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void appRefusesInvalidDirectoryPath() {
    	assertEquals(0, App.checkIfDirectoryEmptyOrInvalid("C:/underoath"), "app should return error if empty folder or invalid");
    }
    @Test public void appRefusesEmptyDirectory() {
    	assertEquals(0, App.checkIfDirectoryEmptyOrInvalid("/app/src/test/resources/BasicSite/emptyDirectory"), "app should return error if empty folder");
    }
    @Test public void appRefusesFile() {
    	assertEquals(0, App.checkIfDirectoryEmptyOrInvalid("/app/src/test/resources/BasicSite/aboutme.html"), "app should return error if just a file");
    }
    @Test public void appRefusesNoArgument() {
    	String[] args = new String[0];
    	assertEquals(0, App.isArgumentProvided(args), "app should return error if just a file");
    }
}
